#Hugo configuration
title = "qwesdf"
baseURL = "https:\/\/wersdf.asd.ewr"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758381"
subfolder = ""
